# Generated by Django 5.0.3 on 2024-03-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='День')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Адрес')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Заголовок')),
                ('information', models.TextField(blank=True, default='', null=True, verbose_name='Информация о мероприятии')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
