# Generated by Django 5.0.3 on 2024-04-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_contact_email_event_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='googleMap_address_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на гугл карту'),
        ),
    ]
