# Generated by Django 5.0.3 on 2024-04-26 13:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_googlemap_address_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона для связи'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='День')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта для связи')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
    ]
