# Generated by Django 5.0.3 on 2024-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_event_contact_phone_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='information',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Информация о этапе'),
        ),
    ]
