# Generated by Django 5.0.3 on 2024-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_stage_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='img',
            field=models.ImageField(default='StageImg/default/kot.png', upload_to='StageImg/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='avatar/default/kot.png', upload_to='avatar/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
